### ISSUE TITLE
Lower CMake version to 3.10

### ISSUE THREAD

**Issue by offa** [offa/influxdb-cxx#98]
Ubuntu 18.04 LTS ships CMake v3.10; see https://github.com/offa/influxdb-cxx/discussions/97.

Related: #27 

/cc @koen-n

**Comment by offa** [comment]
@koen-n if you have some spare time, I have prepared a test branch (`98-cmake_310`). Everything looks fine on latest CMake, but a test on 3.10 would be good.

**Comment by koen-n** [comment]
I've tested the branch with cmake 3.10.2 and I get the following error:
CMake Error at external/influxdb-cxx/src/CMakeLists.txt:19 (target_link_libraries):
  Object library target "InfluxDB-BoostSupport" may not link to anything.
  
 I found some information about it [here](https://github.com/cp2k/dbcsr/issues/266).
 
 When using  cmake 3.12.0 the following error occurs:
 CMake Error at external/influxdb-cxx/CMakeLists.txt:140 (install):
  install TARGETS given target "InfluxDB" which does not exist in this
  directory.
  
That is probably caused by what is stated [here](https://stackoverflow.com/questions/34443128/cmake-install-targets-in-subdirectories), because it works when using cmake 3.13.0.

**Comment by offa** [comment]
Thanks! I'll have a look at it.

**Comment by offa** [comment]
I can reproduce both issues using CMake 3.10.3 / 3.12.4.

The 3.12 one is fixed by the recent commit, the other one needs some more work.

**Comment by offa** [comment]
While 3.12 wasn't that difficult, going down to 3.10 is quite complicated as it doesn't support some features.

Since updating to a more recent version isn't that difficult (in most cases) on the other side, is that an option for you @koen-n.

Ideas, suggestion and – especially – contributions are still welcome though.
